import { enHomeCopy } from "@/lib/i18n/home/en";
import type { HomeCopy } from "@/lib/i18n/types";

export const daHomeCopy = {
  ...enHomeCopy,
  locale: "da",
  metadata: {
    title: "Regards Kim - Shopify-supportsvar med et klik",
    description:
      "Regards Kim sorterer kundemails og vedhæfter Shopify-ordren. Klik på Foreslå svar, gennemgå kladden, og send fra Gmail.",
    ogLocale: "da_DK",
  },
  nav: { ...enHomeCopy.nav, links: [
    { href: "/#how-it-works", label: "Sådan virker det" }, { href: "/demo", label: "Demo" }, { href: "/#pricing", label: "Pris" }, { href: "/#compare", label: "Sammenlign" }, { href: "/security", label: "Sikkerhed" }, { href: "/#faq", label: "FAQ" }, { href: "/about", label: "Om os" }, { href: "/blog", label: "Blog" },
  ], installCta: "Installer på Shopify", menuLabel: "Menu", closeMenuLabel: "Luk menu", openMenuLabel: "Åbn menu", toggleMenuLabel: "Skift navigation", languageLabel: "Sprog" },
  hero: { ...enHomeCopy.hero, title: "Din supportindbakke, besvaret med et klik.", badges: { shopify: "Bygget til Shopify", gmail: "Virker med Gmail" }, body: "Regards Kim sorterer hver kundemail og vedhæfter Shopify-ordren. Klik på Foreslå svar, så er kladden skrevet. Du gennemgår, retter og sender fra Gmail.", primaryCta: "Installer på Shopify", secondaryCta: "Se demoen", workflowPoints: ["Regards Kim sorterer indbakken", "Ordrekontekst vedhæftet", "Klik Foreslå svar", "Du gennemgår og sender"], reassurance: "Ingen autosending · Intet kreditkort · Faktureres via Shopify kun hvis du bliver" },
  howItWorks: { heading: "Sådan virker det", steps: [
    { ...enHomeCopy.howItWorks.steps[0], title: "Forbind Gmail og Shopify", body: "To minutter at forbinde. Regards Kim begynder at sortere kundemails efter emne og filtrerer støj fra: salgspitches, notifikationer og bounces rammer ikke køen.", alt: "Regards Kim sorterer kundemails: tracking-spørgsmål, retur, ordreændring og nyhedsbrev markeret som intet svar nødvendigt" },
    { ...enHomeCopy.howItWorks.steps[1], title: "Hver email kommer med sin ordre", body: "Ordre, leveringsstatus, trackinglinks, politiklinks og kundedetaljer står ved siden af samtalen. Ikke mere jagt gennem faner.", alt: "Kundemail matches automatisk med Shopify-ordre 1842 med status, fragtfirma og trackingnummer" },
    { ...enHomeCopy.howItWorks.steps[2], title: "Klik Foreslå svar, og kladden skrives", body: "Et klik, og Regards Kim skriver et svar baseret på den rigtige ordre. Ingen gæt. Intet skrives eller sendes uden at du beder om det.", video: { ...enHomeCopy.howItWorks.steps[2].video!, ariaLabel: "Merchant klikker Foreslå svar, Regards Kim læser den matchede Shopify-ordre og laver en venlig kladde med rigtigt trackingnummer" } },
  ] },
  comparison: { ...enHomeCopy.comparison, eyebrow: "Se forskellen", heading: "Regards Kim kender din butik.", subheading: "Samme kundespørgsmål. Meget mere kontrol.", genericBadge: "Generisk", productBadge: "Bygget til ecommerce", genericTitle: "Generiske AI-emailværktøjer", genericPoints: ["Bygget til alle indbakker, ikke ecommerce", "Kan ikke se ordre- eller trackingdata", "Kender ikke dine butikspolitikker", "Giver generiske svar uden supportkontekst", "Forstår ikke ecommerce-supportmønstre"], productPoints: ["Bygget specifikt til Shopify-butikker", "Forbinder samtaler med ordrer, tracking og produkter", "Bruger dine rigtige politikker og gemte svar", "Skriver Shopify-bevidste svar i dit normale flow", "Forstår WISMO, returer, ombytninger, ordreændringer og eskaleringer"], customerEmailLabel: "Kundemail", genericReplyLabel: "Generisk AI", draftedReplyLabel: "AI-kladdesvar", replyToLabel: "Til", replySubjectLabel: "Emne", replySubject: "Re: Ordre #4721 - Forsendelsesopdatering", trackingCta: "Se tracking →", signoffLineOne: "Venlig hilsen," },
  proofBand: { ...enHomeCopy.proofBand, eyebrow: "Tidlige merchants", heading: "De første butikker er allerede fri af indbakkevagten.", starsLabel: "5 ud af 5 stjerner" },
  languages: { ...enHomeCopy.languages, eyebrow: "Flersproget support", heading: "Svar på kundens sprog.", body: "Når en kunde skriver på et andet sprog, registrerer Regards Kim sproget og skriver svaret på det sprog, så du kan gennemgå, rette og godkende.", note: "Appens interface findes på engelsk, tysk, spansk, fransk, hollandsk, dansk, svensk, portugisisk (Brasilien) og forenklet kinesisk." },
  costAnchor: { ...enHomeCopy.costAnchor, heading: "Hvad koster support dig lige nu?", body: "Support virker gratis, når det gemmer sig i stiftertimer. Det er det ikke.", options: [
    { title: "Din egen tid", cost: "$500+/mo", body: "Fem timer om ugen på trackingopslag og copy-paste-svar: den dyreste supportagent din butik får.", highlight: false },
    { title: "En deltids-VA", cost: "$800+/mo", body: "Omkring 20 timer om ugen til normale VA-priser plus ansættelse, oplæring, styring og tidszoner.", highlight: false },
    { title: "Regards Kim", cost: "$49/mo", body: "Sortering, ordrekontekst og kladder fra forbindelsen er sat op. Regards Kim melder sig aldrig syg, og du godkender hvert send.", highlight: true },
  ], cta: "Beregn dine tal" },
  trustAndSafety: { ...enHomeCopy.trustAndSafety, eyebrow: "Tillid først", heading: "AI-hjælp til kundemails, med mennesker i kontrol.", body: "Regards Kim er bygget til Shopify-merchants, der vil svare hurtigere uden at overlade kundesamtaler til en uovervåget bot.", points: [
    { title: "Ingen automatisk sending", body: "Kladder klargøres til gennemgang. Et menneske vælger, hvad der sendes fra Gmail." },
    { title: "Bygget omkring Shopify-kontekst", body: "Svar bygger på kundemail, Shopify-ordredata, tracking og dine politikker." },
    { title: "Kundedata beskyttes", body: "Regards Kim bruger kommunikationsdata til dit supportflow, ikke til at sælge data eller træne generelle AI-modeller." },
    { title: "Sikrere end at gætte", body: "Flowet holder ordrefakta, politiklinks og menneskelig godkendelse tæt på hvert svar." },
  ], detailHeading: "Vil du se datadetaljerne før installation?", detailBody: "Læs den klare oversigt over Gmail-adgang, Shopify-tilladelser, AI-brug og hvad Regards Kim gør og ikke gør med kundekommunikation.", detailCta: "Læs Sikkerhed & data" },
  founderNote: { ...enHomeCopy.founderNote, imageAlt: "Matt, stifter af Regards Kim", eyebrow: "En note fra stifteren", quote: "Jeg drev ecommerce-butikker i ti år. Den bedste supportperson jeg arbejdede med, inspirerede Regards Kim: rolig, tydelig og i stand til at gøre en vred kunde loyal på to sætninger. Regards Kim findes, så hver butiksejer kan få den slags hjælp.", attribution: "Matt · Stifter, Regards Kim", link: "Læs hele historien →" },
  pricing: { ...enHomeCopy.pricing, heading: "En plan. En brøkdel af din første supportansættelse.", body: "En deltids-VA starter omkring $800 om måneden. Din egen tid koster mere end du tror. Regards Kim koster $49, arbejder fra det øjeblik du forbinder, og melder sig aldrig syg.", period: "/måned", rateBadge: "Tidlig merchant-pris - låst for livet", billingNote: "Faktureres månedligt via din Shopify-konto", cta: "Installer på Shopify", reassurance: ["7 dages gratis prøve", "Faktureres via Shopify", "Opsig når som helst", "Ingen automatiske kundesvar"], explainerHeading: "Det betaler du for", finalNote: "Start med 7 dages gratis prøve. Behold det kun hvis support bliver lettere." },
  gettingStarted: { ...enHomeCopy.gettingStarted, eyebrow: "Kom i gang", heading: "Installer fra Shopify og kom i gang på minutter", body: "Installer RegardsKim fra Shopify App Store, forbind din indbakke og bekræft dine butikspolitikker, så AI'en har den rigtige kontekst.", steps: [{ number: "01", title: "Installer RegardsKim fra Shopify App Store" }, { number: "02", title: "Forbind din email" }, { number: "03", title: "Bekræft butikspolitikker" }, { number: "04", title: "Åbn din AI-supportindbakke" }] },
  faq: { ...enHomeCopy.faq, heading: "FAQ" },
  finalCta: { heading: "Din indbakke, håndteret.", body: "Installer gratis. Hvis den første uge ikke gør support lettere, kan du gå igen uden kort og uden binding.", cta: "Installer gratis på Shopify", signoff: "Venlig hilsen, Kim" },
  footer: { ...enHomeCopy.footer, description: "AI-drevet kundesupport til Shopify-butikker, hvor hvert kundesvar gennemgås af et menneske før det sendes.", subscribeHeading: "Følg med", subscribeCta: "Tilmeld", successMessage: "Du er på! Vi holder dig opdateret.", errorMessage: "Noget gik galt - prøv igen.", languageHeading: "Sprog", tagline: "Din supportindbakke, drevet af AI.", signoff: "Venlig hilsen, Kim", copyright: "© RegardsKim 2026. Alle rettigheder forbeholdes." },
} satisfies HomeCopy;
