import { enHomeCopy } from "@/lib/i18n/home/en";
import type { HomeCopy } from "@/lib/i18n/types";

export const nlHomeCopy = {
  ...enHomeCopy,
  locale: "nl",
  metadata: {
    title: "Regards Kim - Shopify-supportantwoorden met één klik",
    description:
      "Regards Kim sorteert klantmails, koppelt de Shopify-bestelling en zet AI-concepten klaar om te controleren en via Gmail te versturen.",
    ogLocale: "nl_NL",
  },
  nav: { ...enHomeCopy.nav, links: [
    { href: "/#how-it-works", label: "Zo werkt het" }, { href: "/demo", label: "Demo" }, { href: "/#pricing", label: "Prijs" }, { href: "/#compare", label: "Vergelijken" }, { href: "/security", label: "Beveiliging" }, { href: "/#faq", label: "FAQ" }, { href: "/about", label: "Over ons" }, { href: "/blog", label: "Blog" },
  ], installCta: "Installeren op Shopify", menuLabel: "Menu", closeMenuLabel: "Menu sluiten", openMenuLabel: "Menu openen", toggleMenuLabel: "Navigatie wisselen", languageLabel: "Taal" },
  hero: { ...enHomeCopy.hero, title: "Je support-inbox, voorbereid met AI-concepten.", badges: { shopify: "Gebouwd voor Shopify", gmail: "Werkt met Gmail" }, body: "Regards Kim sorteert elke klantmail, koppelt de Shopify-bestelling en zet het concept automatisch klaar. Jij controleert, bewerkt en verstuurt via Gmail.", primaryCta: "Installeren op Shopify", secondaryCta: "Bekijk de demo", workflowPoints: ["Regards Kim sorteert de inbox", "Bestelcontext gekoppeld", "AI-concept klaar", "Jij controleert en verstuurt"], reassurance: "Geen automatisch verzenden · Geen creditcard · Alleen via Shopify gefactureerd als je blijft" },
  howItWorks: { heading: "Zo werkt het", steps: [
    { ...enHomeCopy.howItWorks.steps[0], title: "Koppel Gmail en Shopify", body: "Verbinden duurt twee minuten. Regards Kim sorteert klantmails per onderwerp en filtert ruis zoals salesmails, meldingen en bounces.", alt: "Regards Kim sorteert klantmails: trackingvraag, retour, orderwijziging en nieuwsbrief zonder antwoord nodig" },
    { ...enHomeCopy.howItWorks.steps[1], title: "Elke mail komt met de juiste bestelling", body: "Bestelling, bezorgstatus, trackinglinks, beleidslinks en klantdetails staan naast het gesprek. Geen zoektocht door tabbladen meer.", alt: "Een klantmail wordt automatisch gekoppeld aan Shopify-bestelling 1842 met status, vervoerder en trackingnummer" },
    { ...enHomeCopy.howItWorks.steps[2], title: "AI zet het concept klaar voordat je de mail opent", body: "Wanneer supportmails binnenkomen, maakt Regards Kim een antwoord op basis van de echte bestelling. Niet gokken. Zonder jouw controle wordt niets verzonden.", video: { ...enHomeCopy.howItWorks.steps[2].video!, ariaLabel: "Regards Kim leest de gekoppelde Shopify-bestelling en maakt een vriendelijk concept met echt trackingnummer" } },
  ] },
  comparison: { ...enHomeCopy.comparison, eyebrow: "Zie het verschil", heading: "Regards Kim kent je winkel.", subheading: "Dezelfde klantvraag. Veel meer controle.", genericBadge: "Algemeen", productBadge: "Gebouwd voor ecommerce", genericTitle: "Algemene AI-mailtools", genericPoints: ["Gebouwd voor elke inbox, niet ecommerce", "Geen toegang tot order- of trackingdata", "Kent je winkelbeleid niet", "Geeft algemene antwoorden zonder context", "Begrijpt ecommerce-supportpatronen niet"], productPoints: ["Speciaal voor Shopify-winkels", "Koppelt gesprekken aan orders, tracking en producten", "Gebruikt je echte beleid en opgeslagen antwoorden", "Maakt Shopify-bewuste concepten in je normale workflow", "Begrijpt WISMO, retouren, ruilingen, orderwijzigingen en escalaties"], customerEmailLabel: "Klantmail", genericReplyLabel: "Algemene AI", draftedReplyLabel: "AI-conceptantwoord", replyToLabel: "Aan", replySubjectLabel: "Onderwerp", replySubject: "Re: Bestelling #4721 - Verzendupdate", trackingCta: "Tracking bekijken →", signoffLineOne: "Met vriendelijke groet," },
  proofBand: { ...enHomeCopy.proofBand, eyebrow: "Eerste merchants", heading: "De eerste winkels zijn al van inboxdienst af.", starsLabel: "5 van 5 sterren" },
  languages: { ...enHomeCopy.languages, eyebrow: "Meertalige support", heading: "Antwoord in de taal van je klant.", body: "Schrijft een klant in een andere taal, dan detecteert Regards Kim die taal en maakt het concept in diezelfde taal zodat jij kunt controleren, bewerken en goedkeuren.", note: "De app-interface is beschikbaar in Engels, Duits, Spaans, Frans, Nederlands, Deens, Zweeds, Portugees (Brazilië) en Vereenvoudigd Chinees." },
  costAnchor: { ...enHomeCopy.costAnchor, heading: "Wat kost support je nu echt?", body: "Support lijkt gratis als het verstopt zit in oprichtersuren. Dat is het niet.", options: [
    { title: "Je eigen tijd", cost: "$500+/mo", body: "Vijf uur per week zoeken naar tracking en copy-paste-antwoorden: de duurste supportmedewerker die je winkel ooit heeft.", highlight: false },
    { title: "Een parttime VA", cost: "$800+/mo", body: "Ongeveer 20 uur per week tegen normale VA-tarieven, plus werving, training, management en tijdzones.", highlight: false },
    { title: "Regards Kim", cost: "$49/mo", body: "Sortering, ordercontext en concepten vanaf het moment van verbinden. Regards Kim meldt zich nooit ziek en jij keurt elke verzending goed.", highlight: true },
  ], cta: "Bereken je cijfers" },
  trustAndSafety: { ...enHomeCopy.trustAndSafety, eyebrow: "Vertrouwen eerst", heading: "AI-hulp voor klantmails, met mensen aan het stuur.", body: "Regards Kim is gemaakt voor Shopify-merchants die sneller willen antwoorden zonder klantgesprekken over te dragen aan een onbeheerde bot.", points: [
    { title: "Geen automatisch verzenden", body: "Concepten zijn er voor review. Een mens kiest wat vanuit Gmail wordt verzonden." },
    { title: "Gebouwd rond Shopify-context", body: "Antwoorden zijn gebaseerd op klantmail, Shopify-ordergegevens, tracking en je beleid." },
    { title: "Klantdata blijft beschermd", body: "Regards Kim gebruikt communicatiedata voor je supportworkflow, niet om data te verkopen of algemene AI-modellen te trainen." },
    { title: "Veiliger dan inbox-gokwerk", body: "De workflow houdt orderfeiten, beleidslinks en menselijke goedkeuring dicht bij elk antwoord." },
  ], detailHeading: "Wil je de datadetails zien voor installatie?", detailBody: "Lees het duidelijke overzicht van Gmail-toegang, Shopify-rechten, AI-gebruik en wat Regards Kim wel en niet doet met klantcommunicatie.", detailCta: "Lees Beveiliging & data" },
  founderNote: { ...enHomeCopy.founderNote, imageAlt: "Matt, oprichter van Regards Kim", eyebrow: "Een bericht van de oprichter", quote: "Ik runde tien jaar ecommercewinkels. De beste supportpersoon met wie ik werkte inspireerde Regards Kim: rustig, duidelijk en in staat om een boze klant in twee zinnen loyaal te maken. Regards Kim bestaat zodat elke winkelier dat soort hulp krijgt.", attribution: "Matt · Oprichter, Regards Kim", link: "Lees het hele verhaal →" },
  pricing: { ...enHomeCopy.pricing, heading: "Eén plan. Een fractie van je eerste supporthire.", body: "Een parttime VA begint rond $800 per maand. Je eigen tijd kost meer dan je denkt. Regards Kim kost $49, werkt zodra je koppelt en meldt zich nooit ziek.", period: "/maand", rateBadge: "Vroege merchantprijs - levenslang vast", billingNote: "Maandelijks gefactureerd via je Shopify-account", cta: "Installeren op Shopify", reassurance: ["7 dagen gratis proef", "Gefactureerd via Shopify", "Altijd opzegbaar", "Geen automatische klantantwoorden"], explainerHeading: "Waarvoor je betaalt", finalNote: "Begin met 7 dagen gratis. Houd het alleen als support lichter wordt." },
  gettingStarted: { ...enHomeCopy.gettingStarted, eyebrow: "Aan de slag", heading: "Installeer via Shopify en start in minuten", body: "Installeer RegardsKim vanuit de Shopify App Store, koppel je inbox en bevestig je winkelbeleid zodat de AI de juiste context heeft.", steps: [{ number: "01", title: "Installeer RegardsKim vanuit de Shopify App Store" }, { number: "02", title: "Koppel je email" }, { number: "03", title: "Bevestig je winkelbeleid" }, { number: "04", title: "Open je AI-supportinbox" }] },
  faq: { ...enHomeCopy.faq, heading: "FAQ" },
  finalCta: { heading: "Je inbox, geregeld.", body: "Installeer gratis. Maakt de eerste week support niet lichter, dan stop je zonder kaart en zonder lock-in.", cta: "Gratis installeren op Shopify", signoff: "Met vriendelijke groet, Kim" },
  footer: { ...enHomeCopy.footer, description: "AI-klantsupport voor Shopify-winkels, waarbij elk klantantwoord voor verzending door een mens wordt gecontroleerd.", subscribeHeading: "Blijf op de hoogte", subscribeCta: "Abonneren", successMessage: "Je staat erop! We houden je op de hoogte.", errorMessage: "Er ging iets mis - probeer opnieuw.", languageHeading: "Taal", tagline: "Je support-inbox, aangedreven door AI.", signoff: "Met vriendelijke groet, Kim", copyright: "© RegardsKim 2026. Alle rechten voorbehouden." },
} satisfies HomeCopy;
