import { enHomeCopy } from "@/lib/i18n/home/en";
import type { HomeCopy } from "@/lib/i18n/types";

export const svHomeCopy = {
  ...enHomeCopy,
  locale: "sv",
  metadata: {
    title: "Regards Kim - Shopify-supportsvar med ett klick",
    description:
      "Regards Kim sorterar kundmejl och bifogar Shopify-ordern. Klicka på Föreslå svar, granska utkastet och skicka från Gmail.",
    ogLocale: "sv_SE",
  },
  nav: { ...enHomeCopy.nav, links: [
    { href: "/#how-it-works", label: "Så funkar det" }, { href: "/demo", label: "Demo" }, { href: "/#pricing", label: "Pris" }, { href: "/#compare", label: "Jämför" }, { href: "/security", label: "Säkerhet" }, { href: "/#faq", label: "FAQ" }, { href: "/about", label: "Om oss" }, { href: "/blog", label: "Blogg" },
  ], installCta: "Installera på Shopify", menuLabel: "Meny", closeMenuLabel: "Stäng meny", openMenuLabel: "Öppna meny", toggleMenuLabel: "Växla navigering", languageLabel: "Språk" },
  hero: { ...enHomeCopy.hero, title: "Din supportinkorg, besvarad med ett klick.", badges: { shopify: "Byggd för Shopify", gmail: "Fungerar med Gmail" }, body: "Regards Kim sorterar varje kundmejl och bifogar Shopify-ordern. Klicka på Föreslå svar så skrivs utkastet. Du granskar, redigerar och skickar från Gmail.", primaryCta: "Installera på Shopify", secondaryCta: "Se demon", workflowPoints: ["Regards Kim sorterar inkorgen", "Orderkontext bifogad", "Klicka Föreslå svar", "Du granskar och skickar"], reassurance: "Ingen autosändning · Inget kort · Faktureras via Shopify bara om du stannar" },
  howItWorks: { heading: "Så funkar det", steps: [
    { ...enHomeCopy.howItWorks.steps[0], title: "Koppla Gmail och Shopify", body: "Två minuter att koppla. Regards Kim börjar sortera kundmejl efter ärende och filtrerar bort brus som säljpitchar, notifieringar och studsar.", alt: "Regards Kim sorterar kundmejl: spårningsfråga, retur, orderändring och nyhetsbrev markerat som inget svar behövs" },
    { ...enHomeCopy.howItWorks.steps[1], title: "Varje mejl kommer med rätt order", body: "Order, leveransstatus, spårningslänkar, policylänkar och kunduppgifter står bredvid konversationen. Inget flikletande.", alt: "Kundmejl matchas automatiskt med Shopify-order 1842 med status, fraktbolag och spårningsnummer" },
    { ...enHomeCopy.howItWorks.steps[2], title: "Klicka Föreslå svar och utkastet skrivs", body: "Ett klick och Regards Kim skriver ett svar baserat på den riktiga ordern. Inga gissningar. Inget skrivs eller skickas utan att du ber om det.", video: { ...enHomeCopy.howItWorks.steps[2].video!, ariaLabel: "Handlaren klickar Föreslå svar, Regards Kim läser den matchade Shopify-ordern och skapar ett vänligt utkast med riktigt spårningsnummer" } },
  ] },
  comparison: { ...enHomeCopy.comparison, eyebrow: "Se skillnaden", heading: "Regards Kim känner din butik.", subheading: "Samma kundfråga. Mycket mer kontroll.", genericBadge: "Generiskt", productBadge: "Byggt för ecommerce", genericTitle: "Generiska AI-mejlverktyg", genericPoints: ["Byggda för alla inkorgar, inte ecommerce", "Kommer inte åt order- eller spårningsdata", "Känner inte dina butikspolicyer", "Ger generiska svar utan supportkontext", "Förstår inte ecommerce-supportmönster"], productPoints: ["Byggt specifikt för Shopify-butiker", "Kopplar samtal till ordrar, spårning och produkter", "Använder dina riktiga policyer och sparade svar", "Skriver Shopify-medvetna svar i ditt vanliga flöde", "Förstår WISMO, returer, byten, orderändringar och eskaleringar"], customerEmailLabel: "Kundmejl", genericReplyLabel: "Generisk AI", draftedReplyLabel: "AI-skrivet svar", replyToLabel: "Till", replySubjectLabel: "Ämne", replySubject: "Re: Order #4721 - Leveransuppdatering", trackingCta: "Visa spårning →", signoffLineOne: "Vänliga hälsningar," },
  proofBand: { ...enHomeCopy.proofBand, eyebrow: "Tidiga handlare", heading: "De första butikerna är redan fria från inkorgspasset.", starsLabel: "5 av 5 stjärnor" },
  languages: { ...enHomeCopy.languages, eyebrow: "Flerspråkig support", heading: "Svara på kundens språk.", body: "När en kund skriver på ett annat språk känner Regards Kim igen språket och skriver utkastet på samma språk så att du kan granska, redigera och godkänna.", note: "Appens gränssnitt finns på engelska, tyska, spanska, franska, nederländska, danska, svenska, portugisiska (Brasilien) och förenklad kinesiska." },
  costAnchor: { ...enHomeCopy.costAnchor, heading: "Vad kostar support dig just nu?", body: "Support ser gratis ut när den gömmer sig i grundartid. Det är den inte.", options: [
    { title: "Din egen tid", cost: "$500+/mo", body: "Fem timmar i veckan på spårningsletande och copy-paste-svar: den dyraste supportagenten din butik någonsin får.", highlight: false },
    { title: "En deltids-VA", cost: "$800+/mo", body: "Ungefär 20 timmar i veckan till vanliga VA-priser, plus rekrytering, utbildning, styrning och tidszoner.", highlight: false },
    { title: "Regards Kim", cost: "$49/mo", body: "Sortering, orderkontext och utkast från stunden du kopplar. Regards Kim sjukskriver sig aldrig, och du godkänner varje sändning.", highlight: true },
  ], cta: "Räkna på dina siffror" },
  trustAndSafety: { ...enHomeCopy.trustAndSafety, eyebrow: "Förtroende först", heading: "AI-hjälp för kundmejl, med människor i kontroll.", body: "Regards Kim är byggt för Shopify-handlare som vill svara snabbare utan att lämna kundsamtal till en obevakad bot.", points: [
    { title: "Ingen automatisk sändning", body: "Utkast förbereds för granskning. En människa väljer vad som skickas från Gmail." },
    { title: "Byggt runt Shopify-kontext", body: "Svar bygger på kundmejl, Shopify-orderdetaljer, spårning och dina policyer." },
    { title: "Kunddata skyddas", body: "Regards Kim använder kommunikationsdata för ditt supportflöde, inte för att sälja data eller träna allmänna AI-modeller." },
    { title: "Säkrare än att gissa", body: "Flödet håller orderfakta, policylänkar och mänskligt godkännande nära varje kundsvar." },
  ], detailHeading: "Vill du se datadetaljerna innan installation?", detailBody: "Läs den tydliga översikten av Gmail-åtkomst, Shopify-behörigheter, AI-användning och vad Regards Kim gör och inte gör med kundkommunikation.", detailCta: "Läs Säkerhet & data" },
  founderNote: { ...enHomeCopy.founderNote, imageAlt: "Matt, grundare av Regards Kim", eyebrow: "En hälsning från grundaren", quote: "Jag drev ecommerce-butiker i tio år. Den bästa supportpersonen jag arbetade med inspirerade Regards Kim: lugn, tydlig och kunde göra en arg kund lojal på två meningar. Regards Kim finns för att varje butiksägare ska få den sortens hjälp.", attribution: "Matt · Grundare, Regards Kim", link: "Läs hela berättelsen →" },
  pricing: { ...enHomeCopy.pricing, heading: "En plan. En bråkdel av din första supportanställning.", body: "En deltids-VA börjar runt $800 i månaden. Din egen tid kostar mer än du tror. Regards Kim kostar $49, arbetar direkt när du kopplar och sjukskriver sig aldrig.", period: "/månad", rateBadge: "Tidigt handlarpris - låst för livet", billingNote: "Faktureras månadsvis via ditt Shopify-konto", cta: "Installera på Shopify", reassurance: ["7 dagars gratis provperiod", "Faktureras via Shopify", "Avsluta när som helst", "Inga automatiska kundsvar"], explainerHeading: "Vad du betalar för", finalNote: "Börja med 7 dagar gratis. Behåll bara om supporten blir lättare." },
  gettingStarted: { ...enHomeCopy.gettingStarted, eyebrow: "Kom igång", heading: "Installera från Shopify och kom igång på minuter", body: "Installera RegardsKim från Shopify App Store, koppla din inkorg och bekräfta butikens policyer så att AI har rätt kontext.", steps: [{ number: "01", title: "Installera RegardsKim från Shopify App Store" }, { number: "02", title: "Koppla din e-post" }, { number: "03", title: "Bekräfta butikens policyer" }, { number: "04", title: "Öppna din AI-supportinkorg" }] },
  faq: { ...enHomeCopy.faq, heading: "FAQ" },
  finalCta: { heading: "Din inkorg, hanterad.", body: "Installera gratis. Om första veckan inte gör supporten lättare kan du lämna utan kort och utan bindning.", cta: "Installera gratis på Shopify", signoff: "Vänliga hälsningar, Kim" },
  footer: { ...enHomeCopy.footer, description: "AI-driven kundsupport för Shopify-butiker där varje kundsvar granskas av en människa innan det skickas.", subscribeHeading: "Håll dig uppdaterad", subscribeCta: "Prenumerera", successMessage: "Du är med! Vi håller dig uppdaterad.", errorMessage: "Något gick fel - försök igen.", languageHeading: "Språk", tagline: "Din supportinkorg, driven av AI.", signoff: "Vänliga hälsningar, Kim", copyright: "© RegardsKim 2026. Alla rättigheter förbehållna." },
} satisfies HomeCopy;
